pre-commit:
  parallel: true
  commands:
    eslint:
      glob: "*.{js,jsx,ts,tsx}"
      run: eslint --fix {staged_files}
    prettier:
      glob: "*.{js,ts,jsx,tsx,json,yml,yaml,toml,md,html,css,scss,sass}"
      run: prettier --write {staged_files}

pre-push:
  commands:
    packages-audit:
      run: yarn audit
